# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0ef70580998cd3ac21447e1ce5efc1a4d169ec339acc2c3b405f3b8346f864058cfa1088917925f8e507e45053cfb3c3001d53f81354092bec219650bf885145

test:
  secret_key_base: 5e5e62059a3604566e5e88d24cfd9087fbce964f3a80c311b8875e5f3b078f1d3f9fd12f62ec36fe151c00486b2bc429d522c28b8f2ff0131b6be95d1fb28761

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
